version: '3.7'

networks:
  app-network:
    driver: bridge

services:
    npm: 
      build: 
        context: ./
        dockerfile: Dockerfile
      container_name: aac-node
      working_dir: /var/www
      entrypoint: ['npm']
      volumes: 
        - ./:/var/www
      networks: 
        - app-network 

    nginx:
        image: nginx:1.19.8-alpine
        container_name: aac-nginx
        restart: unless-stopped
        tty: true
        ports: 
            - 8101:80
        volumes: 
            - ./:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network
